import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@styles/globals.css';
import { gsap } from 'gsap';
import { CustomEase } from 'gsap/CustomEase';
import { SmoothProvider, StoreProvider, TransitionProvider } from '@components-providers';
import { GoogleAnalytics } from '@shared-lib';
import { Syne } from 'next/font/google';
import { AppHeader, AppHeaderWrapper } from '@components-layout';
import { Cursor } from '@components-ui';

gsap.registerPlugin(CustomEase);

const satoshi = localFont({
  src: '../assets/fonts/satoshi/Satoshi-Variable.woff2',
  style: 'normal',
  variable: '--font-satoshi',
});

const syne = Syne({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-syne',
});

export const metadata: Metadata = {
  title: 'Ihor Yanchuk • Frontend & Fullstack Developer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
          rel="stylesheet"
        ></link>
        <link
          rel="icon"
          type="image/png"
          href="/favicons/favicon-96x96.png"
          sizes="96x96"
        />
        <link rel="icon" type="image/svg+xml" href="/favicons/favicon.svg" />
        <link rel="shortcut icon" href="/favicons/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicons/apple-touch-icon.png"
        />
        <meta name="apple-mobile-web-app-title" content="YanchukDev" />
        <link rel="manifest" href="/favicons/site.webmanifest" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no"
        ></meta>
        <GoogleAnalytics />
      </head>

      <body className={`${satoshi.variable} ${syne.variable}`}>
        <StoreProvider>
          <SmoothProvider>
            <Cursor />
            <AppHeader />
            <AppHeaderWrapper />
            <TransitionProvider>{children}</TransitionProvider>
          </SmoothProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
