export const STACK_ITEMS = [
    'REACT.JS', 'NEXT.JS', "AXIOS", 'TYPESCRIPT', "STORYBOOK", 'GSAP', "RTK QUERY", "REDUX", "SHADCN", "JEST", 'TAILWIND',
    'NODE.JS', 'POSTGRESQL', 'PRISMA', "ZUSTAND", "REACT NATIVE", 'FRAMER MOTION', "MSW", "FIREBASE", 'THREE.JS',
];